# Generated by Django 5.0.6 on 2024-06-05 19:02

import cadastros.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nome_completo', models.CharField(help_text='Digite o nome completo', max_length=100)),
                ('username', models.CharField(default=cadastros.models.generate_random_string, max_length=8, unique=True)),
                ('email', models.EmailField(help_text='Digite o email', max_length=254, unique=True)),
                ('celular', models.CharField(max_length=15)),
                ('setor', models.CharField(max_length=100)),
                ('status', models.BooleanField(choices=[(True, 'Ativo'), (False, 'Inativo')], default=True)),
                ('observacoes', models.TextField(blank=True, help_text='Adicione quaisquer observações adicionais sobre o usuário', null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('cargo', models.ForeignKey(help_text='Selecione o cargo...', on_delete=django.db.models.deletion.CASCADE, to='cadastros.cargo')),
                ('orgao', models.ForeignKey(help_text='Selecione o orgão...', on_delete=django.db.models.deletion.CASCADE, to='cadastros.orgao')),
                ('tipo_acesso', models.ForeignKey(help_text='Selecione o tipo de acesso...', on_delete=django.db.models.deletion.CASCADE, to='cadastros.tipoacesso')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
